### ISSUE TITLE
Vunerability due to using Kind Of 6.0.2

### ISSUE THREAD

**Issue by shawnpringle** [micromatch/nanomatch#25]
_(Thanks for reporting an issue to nanomatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then procede to fill out the details below.)_

## Please describe the **minimum necessary steps** to reproduce this issue:
npm install
…

## What is happening (but shouldn't):
[Vulnerability reported because it names kindof 6.0.2 as a dependency.](https://npmjs.com/advisories/1490)

…

## What should be happening instead?
Name kindof 6.0.3 as a dependency pending a review on whether the API of kind of has changed in a patch number version and testing.
…

**Comment by jonschlinkert** [comment]
These kinds of issues are completely unnecessary. Dependabot and NPM, and Snyk already do this job. Moreover, this isn't a vulnerability.
