### ISSUE TITLE
regex-not 1.0.1 is broken

### ISSUE THREAD

**Issue by stanleyxu2005** [micromatch/nanomatch#8]
https://github.com/micromatch/nanomatch/blob/15fa58f36a516aa2dd5ea70bef5dec2bc3ff7c81/package.json#L37

As regex-not new version 1.0.1 is [broken](https://github.com/jonschlinkert/regex-not/issues/3), my application is failed to deploy on a fresh environment today. Do you think about cherry-pick policy to choose version `"1.0.0"` of this lib is better than having `"^1.0.0"`?

**Comment by groie** [comment]
We have a similar issue since today. With package-lock.json things work fine, but when we update the nanomatch to 1.2.9 (from 1.2.7) our world stops working with a regex-not problem.

**Comment by jonschlinkert** [comment]
This was resolved last night https://github.com/jonschlinkert/regex-not/issues/3#issuecomment-366850811

**Comment by groie** [comment]
in case someone reads this: 1.0.1 and 1.0.2 of regex-not were released very close to eachother. For some reason our internal npm-repository (nexus) had cached 1.0.1 and decided not to look for 1.0.2 in npmjs-repository. Thus all our builds were resolving to 1.0.1.

Solution was to **invalidate the cache of our nexus-npmjs repository** and thus everybody became a tad happier.

**Comment by stanleyxu2005** [comment]
@groie Here is what I have done: `regex-not` is not a direct dependency, so I define `"regex-not": "1.0.0"` in package.json, so that npm will resolve the dependencies and decide to use 1.0.0.

**Comment by jonschlinkert** [comment]
> Solution was to invalidate the cache of our nexus-npmjs repository and thus everybody became a tad happier.

The solution in https://github.com/micromatch/nanomatch/issues/8#issuecomment-366962549 is what should be done.
